apiVersion: v1
kind: Service
metadata:
  name: monitoring-agent-app
  labels:
    app: monitoring-agent-app
spec:
  selector:
    app: monitoring-agent-app
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP