apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring-agent-app-ingress
  annotations:
    # Nginx ingress specific annotations
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: monitoring-agent-app.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: monitoring-agent-app
                port:
                  number: 8000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 5000
          - path: /metrics
            pathType: Prefix
            backend:
              service:
                name: monitoring-agent-app
                port:
                  number: 8000
          - path: /backend-metrics
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 5000